name: Release to PyPi

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [release-python]

jobs:
  release-python:
    runs-on: [self-hosted, Linux]

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # see https://github.com/peter-evans/repository-dispatch
      # - name: Dispatch Payload
      #   run: echo ${{ github.event.client_payload }}
        
      - name: Upload to PyPi
        run: |
          source /__/devbox/.env.sh
          mkdir sling/bin

          cd sling/bin
          wget -q https://ocral.nyc3.digitaloceanspaces.com/slingdata.io/dist/sling-linux
          wget -q https://ocral.nyc3.digitaloceanspaces.com/slingdata.io/dist/sling-mac
          wget -q https://ocral.nyc3.digitaloceanspaces.com/slingdata.io/dist/sling-win.exe
          cd -

          chmod -R 755 sling/bin
          sling/bin/sling-linux --version

          pip install -e .
          pip install twine
          python setup.py sdist && twine upload --verbose --skip-existing dist/*